<?php

namespace Database\Seeders;

use App\Models\Party;
use Illuminate\Database\Seeder;

class PartySeeder extends Seeder
{
    /**
     * Comprehensive party data scraped from Bangladesh Election Commission
     * Source: https://www.ecs.gov.bd/page/political-parties-details
     * Date: November 2025
     */
    public function run(): void
    {
        $parties = [

            [
                'name' => 'বাংলাদেশ জাতীয়তাবাদী দল (বিএনপি)',
                'name_en' => 'Bangladesh Nationalist Party (BNP)',
                'logo' => null,
                'symbol_id' => 6, // ধানের শীষ (sheaf-of-paddy)
                'color' => '#00923F',
                'founded' => '১৯৭৮',
                'registration_number' => '007',
                'registration_date' => '2008-11-03',
                'chairman' => 'বেগম খালেদা জিয়া',
                'secretary_general' => 'মির্জা ফখরুল ইসলাম আলমগীর',
                'office_address' => 'কেন্দ্রীয় কার্যালয় ২৮/১, নয়াপল্টন (ভি আই পি রোড), ঢাকা-১০০০',
                'phone' => '9361064',
                'fax' => '8318687',
                'mobile' => '01720385491',
                'email' => 'bnpcentral@gmail.com',
				'website' => 'www.bnpbd.org',
            ],
            [
                'name' => 'বাংলাদেশ জামায়াতে ইসলামী',
                'name_en' => 'Bangladesh Jamaat-e-Islami',
                'logo' => null,
                'symbol_id' => 13, // দাঁড়িপাল্লা (scales)
                'color' => '#006747',
                'founded' => '১৯৪১',
                'registration_number' => '014',
                'registration_date' => '2008-11-04',
                'chairman' => 'ডা. শফিকুর রহমান',
                'secretary_general' => 'অধ্যাপক মিয়া গোলাম পরওয়ার',
                'office_address' => '৫০৫, এলিফ্যান্ট রোড, বড় মগবাজার, ঢাকা-১২১৭',
                'phone' => '02 222225135, 02 222225136',
                'mobile' => '01610646595, 01743168339',
                'email' => 'info@jamaat-e-islami.org',
				'website' => 'www.jamaat-e-islami.org',
            ],
            [
                'name' => 'জাতীয় নাগরিক পার্টি (এনসিপি)',
                'name_en' => 'National Citizens Party (NCP)',
                'logo' => null,
                'symbol_id' => 54, // শাপলার কলি (water-lily-bud) - New party gets new symbol
                'color' => '#FF6B35',
                'founded' => '2025',
                'registration_number' => null,
                'registration_date' => null,
                'chairman' => 'মো: নাহিদ ইসলাম',
                'secretary_general' => 'আখতার হোসেন',
                'office_address' => 'রূপায়ন ট্রেড সেন্টার, লেভেল ১৫, কাজী নজরুল ইসলাম এভিনিউ, ঢাকা',
                'phone' => '02 222225135, 02 222225136',
                'mobile' => '01759209177',
                'email' => 'contact@ncpbd.org',
				'website' => 'www.ncpbd.org',
            ],
            [
                'name' => 'লিবারেল ডেমোক্রেটিক পার্টি - এলডিপি',
                'name_en' => 'liberal-democratic-party',
                'logo' => null,
                'symbol_id' => 1, // ছাতা (umbrella)
                'color' => '#0066CC',
                'founded' => '২০০৮',
                'registration_number' => '001',
                'registration_date' => '2008-10-20',
                'chairman' => 'ডক্টর অলি আহমদ, বীর বিক্রম',
                'secretary_general' => 'ডক্টর রেদোয়ান আহমেদ',
                'office_address' => 'মগবাজার গুলফেশী প্লাজা, ৯ম তলা, ৮-বি,৮, শহীদ সাংবাদিক সেলিনা পারভীন সড়ক, (৬৯, আউটার সারকুলার সড়ক) মগবাজার, ঢাকা-১২১৭',
                'phone' => '9833766',
                'mobile' => '01979-411308',
                'email' => 'ldp@gmail.com',
                'website' => 'www.ldp-bangladesh.org',
            ],
            [
                'name' => 'জাতীয় পার্টি - জেপি',
                'name_en' => 'jatiya-party-jp',
                'logo' => null,
                'symbol_id' => 2, // বাইসাইকেল (bicycle)
                'color' => '#F42A41',
                'founded' => '২০০৮',
                'registration_number' => '002',
                'registration_date' => '2008-10-20',
                'chairman' => 'আনোয়ার হোসেন মঞ্জু',
                'secretary_general' => 'শেখ শহীদুল ইসলাম',
                'office_address' => '৫/৫, ব্লক-এ, লালমাটিয়া, মোহাম্মদপুর, ঢাকা-১২০৭',
                'phone' => '0258155590',
                'mobile' => '01712-025137',
                'email' => 'jatiyaparty_jp@yahoo.com',
            ],
            [
                'name' => 'বাংলাদেশের সাম্যবাদী দল (এম.এল)',
                'name_en' => 'bangladesher-samyabadi-dal-ml',
                'logo' => null,
                'symbol_id' => 3, // চাকা (wheel)
                'color' => '#DC143C',
                'founded' => '২০০৮',
                'registration_number' => '003',
                'registration_date' => '2008-11-03',
                'secretary_general' => 'মিঃ দিলীপ বড়ুয়া',
                'office_address' => '২৭/১১/১ তোপখানা রোড, ঢাকা-১০০০',
                'phone' => '9565800',
                'mobile' => '01711-594524',
            ],
            [
                'name' => 'কৃষক শ্রমিক জনতা লীগ',
                'name_en' => 'krishak-sramik-janata-league',
                'logo' => null,
                'symbol_id' => 4, // গামছা (gamchha)
                'color' => '#228B22',
                'founded' => '২০০৮',
                'registration_number' => '004',
                'registration_date' => '2008-11-03',
                'chairman' => 'বঙ্গবীর কাদের সিদ্দিকী, বীর উত্তম',
                'secretary_general' => 'হাবিবুর রহমান তালুকদার বীর প্রতীক',
                'office_address' => '৮০, মতিঝিল, জীবন বীমা ভবন (নীচতলা), ঢাকা-১০০০',
                'phone' => '8114393',
                'fax' => '9140023',
                'mobile' => '01721260515',
                'email' => 'ksjanataleague@gmail.com',
            ],
            [
                'name' => 'বাংলাদেশের কমিউনিস্ট পার্টি',
                'name_en' => 'communist-party-of-bangladesh',
                'logo' => null,
                'symbol_id' => 5, // কাস্তে (sickle)
                'color' => '#DC143C',
                'founded' => '২০০৮',
                'registration_number' => '005',
                'registration_date' => '2008-11-03',
                'chairman' => 'মোহাম্মদ শাহ আলম',
                'secretary_general' => 'রুহিন হোসেন প্রিন্স',
                'office_address' => 'মুক্তিভবন-৬ষ্ঠ তলা, ২, কমরেড মণি সিংহ সড়ক, পুরানা পল্টন, ঢাকা-১০০০',
                'phone' => '9558612, 9582483',
                'fax' => '9552333',
                'mobile' => '01711-438181',
                'email' => 'cpbmedia@gmail.com',
                'website' => 'www.cpbbd.org',
            ],
            [
                'name' => 'গণতন্ত্রী পার্টি',
                'name_en' => 'gonotantri-party',
                'logo' => null,
                'symbol_id' => 7, // কবুতর (dove)
                'color' => '#4169E1',
                'founded' => '২০০৮',
                'registration_number' => '008',
                'registration_date' => '2008-11-03',
                'chairman' => 'ব্যারিষ্টার মোঃ আরশ আলী',
                'secretary_general' => 'ডাঃ শাহাদাত হোসেন',
                'office_address' => '৬ পুরানা পল্টন (ইশরাত টাওয়ার, ১০ম তলা), ঢাকা-১০০০',
                'phone' => '9330584',
                'mobile' => '01711-831904, 01718-370112',
                'email' => 'ganotantryparty2015@gmail.com',
            ],
            [
                'name' => 'বাংলাদেশ ন্যাশনাল আওয়ামী পার্টি',
                'name_en' => 'bangladesh-national-awami-party',
                'logo' => null,
                'symbol_id' => 8, // কুঁড়েঘর (hut)
                'color' => '#8B4513',
                'founded' => '২০০৮',
                'registration_number' => '009',
                'registration_date' => '2008-11-03',
                'chairman' => 'আইভি আহমেদ',
                'secretary_general' => 'মোহাম্মদ আলী ফারুক',
                'office_address' => '২০-২১, ধানমন্ডি হকার্স মার্কেট (২য় তলা), ঢাকা-১২০৫',
                'phone' => '02-44611922',
                'mobile' => '01711541542, 01815005038',
            ],
            [
                'name' => 'বাংলাদেশের ওয়ার্কার্স পার্টি',
                'name_en' => 'workers-party-of-bangladesh',
                'logo' => null,
                'symbol_id' => 9, // হাতুড়ী (hammer)
                'color' => '#DC143C',
                'founded' => '২০০৮',
                'registration_number' => '010',
                'registration_date' => '2008-11-03',
                'chairman' => 'রাশেদ খান মেনন',
                'secretary_general' => 'ফজলে হোসেন বাদশা',
                'office_address' => '৩১/এফ, তোপখানা রোড, ঢাকা-১০০০',
                'phone' => '02-9567975',
                'fax' => '02-9558545',
                'email' => 'wpartymail@gmail.com',
            ],
            [
                'name' => 'বিকল্পধারা বাংলাদেশ',
                'name_en' => 'bikalpadhara-bangladesh',
                'logo' => null,
                'symbol_id' => 10, // কুলা (winnowing-fan)
                'color' => '#FF8C00',
                'founded' => '২০০৮',
                'registration_number' => '011',
                'registration_date' => '2008-11-03',
                'chairman' => 'অধ্যাপক এ কিউ এম বদরুদ্দোজা চৌধুরী',
                'secretary_general' => 'মেজর (অবঃ) আবদুল মান্নান',
                'office_address' => 'বাড়ী নং- ১৯, রোড নং- ১২, ব্লক- কে, বারিধারা, ঢাকা-১২১২',
                'phone' => '8855252',
                'fax' => '9890978, 9885647',
                'mobile' => '01913372200',
                'email' => 'bchowdhury@dbn-bd.net, abdulmannan@gmail.com',
            ],
            [
                'name' => 'জাতীয় পার্টি',
                'name_en' => 'jatiya-party',
                'logo' => null,
                'symbol_id' => 11, // লাঙ্গল (plough)
                'color' => '#FF6347',
                'founded' => '১৯৮৬',
                'registration_number' => '012',
                'registration_date' => '2008-11-03',
                'chairman' => 'গোলাম মোহাম্মদ কাদের',
                'secretary_general' => 'মোঃ মুজিবুল হক',
                'office_address' => '৬৬, পাইওনিয়ার রোড, কাকরইল, ঢাকা-১০০০',
                'phone' => '9331705, 9331707, 9331727',
                'fax' => '9331705',
                'mobile' => '01711662828',
                'email' => 'press.jatiyoparty@gmail.com',
            ],
            [
                'name' => 'জাতীয় সমাজতান্ত্রিক দল-জাসদ',
                'name_en' => 'jatiya-samajtantrik-dal-jasad',
                'logo' => null,
                'symbol_id' => 12, // মশাল (torch)
                'color' => '#FF4500',
                'founded' => '২০০৮',
                'registration_number' => '013',
                'registration_date' => '2008-11-03',
                'chairman' => 'হাসানুল হক ইনু',
                'secretary_general' => 'শিরীন আখতার',
                'office_address' => '৩৫-৩৬, বঙ্গবন্ধু এভিনিউ, ঢাকা-১০০০',
                'phone' => '223380173',
                'fax' => '9559972',
                'email' => 'jsd@dhaka.net',
            ],
            [
                'name' => 'জাতীয় সমাজতান্ত্রিক দল-জেএসডি',
                'name_en' => 'jatiya-samajtantrik-dal-jsd',
                'logo' => null,
                'symbol_id' => 14, // তারা (star)
                'color' => '#FFD700',
                'founded' => '২০০৮',
                'registration_number' => '015',
                'registration_date' => '2008-11-09',
                'chairman' => 'আ স ম আবদুর রব',
                'secretary_general' => 'শহীদ উদ্দিন মাহমুদ স্বপন',
                'office_address' => '৬৫, বঙ্গবন্ধু এভিনিউ (৪র্থ তলা), ঢাকা-১০০০',
                'phone' => '9585155',
                'mobile' => '01711561061, 01819263749',
                'email' => 'jsdoffice.1972@gmail.com',
            ],
            [
                'name' => 'জাকের পার্টি',
                'name_en' => 'zaker-party',
                'logo' => null,
                'symbol_id' => 15, // গোলাপ ফুল (rose)
                'color' => '#FF1493',
                'founded' => '২০০৮',
                'registration_number' => '016',
                'registration_date' => '2008-11-09',
                'chairman' => 'মোস্তফা আমীর ফয়সল',
                'secretary_general' => 'শামীম হায়দার',
                'office_address' => 'বাড়ি নং#১৯,ব্লক# আই রোড#৩, বনানী, ঢাকা- ১২১৩',
                'phone' => '9895510',
                'mobile' => '01786222336, 01712904200, 01712188590',
            ],
            [
                'name' => 'বাংলাদেশের সমাজতান্ত্রিক দল-বাসদ',
                'name_en' => 'socialist-party-of-bangladesh-basad',
                'logo' => null,
                'symbol_id' => 16, // মই (ladder)
                'color' => '#DC143C',
                'founded' => '২০০৮',
                'registration_number' => '017',
                'registration_date' => '2008-11-09',
                'secretary_general' => 'কমরেড বজলুর রশীদ ফিরোজ',
                'office_address' => '২৩/২ তোপখানা রোড (৩য় তলা), থানা- শাহবাগ, জিপিও ঢাকা- ১০০০',
                'phone' => '9582206',
                'fax' => '9554772',
                'email' => 'mail@spb.org.bd',
            ],
            [
                'name' => 'বাংলাদেশ জাতীয় পার্টি-বিজেপি',
                'name_en' => 'bangladesh-jatiya-party-bjp',
                'logo' => null,
                'symbol_id' => 17, // গরুরগাড়ী (bullock-cart)
                'color' => '#8B4513',
                'founded' => '২০০৮',
                'registration_number' => '018',
                'registration_date' => '2008-11-09',
                'chairman' => 'ব্যারিষ্টার আন্দালিভ রহমান',
                'office_address' => '৫০, ডি আই টি এক্সটেনশন রোড, ইষ্টার্ণভিউ (৫ম তলা), নয়া পল্টন, ঢাকা-১০০০',
                'phone' => '8317634',
                'fax' => '8319694',
            ],
            [
                'name' => 'বাংলাদেশ তরিকত ফেডারেশন',
                'name_en' => 'bangladesh-tarikat-federation',
                'logo' => null,
                'symbol_id' => 18, // ফুলের মালা (garland)
                'color' => '#FF69B4',
                'founded' => '২০০৮',
                'registration_number' => '019',
                'registration_date' => '2008-11-09',
                'chairman' => 'আলহাজ্ব সৈয়দ নজিবুল বশর মাইজভান্ডারী এম পি',
                'secretary_general' => 'আলহাজ্ব ডঃ সৈয়দ রেজাউল হক চাঁদপুরী',
                'office_address' => 'ফ্ল্যাট নংএ-১, বাড়ী নং ৫১/এ, রোড নং ৬/এ, ধানমন্ডি আ/এ, ঢাকা',
                'phone' => '02-88-9143356',
                'mobile' => '01912756872, 01911597527',
                'email' => 'lnmaawal@yahoo.com',
            ],
            [
                'name' => 'বাংলাদেশ খেলাফত আন্দোলন',
                'name_en' => 'bangladesh-khilafat-andolon',
                'logo' => null,
                'symbol_id' => 19, // বটগাছ (banyan-tree)
                'color' => '#228B22',
                'founded' => '২০০৮',
                'registration_number' => '020',
                'registration_date' => '2008-11-13',
                'chairman' => 'হযরত মাওলানা হাফেজ আতাউল্লাহ ইবনে হাফেজ্জী রহ.',
                'secretary_general' => 'মাওলানা হাবীবুল্লাহ মিয়াজী',
                'office_address' => '৩১৪/২, জে এন সাহা রোড, কিল্লার মোড়, লালবাগ, ঢাকা-১২১১',
                'phone' => '9660097, 9630102',
            ],
            [
                'name' => 'বাংলাদেশ মুসলিম লীগ',
                'name_en' => 'bangladesh-muslim-league',
                'logo' => null,
                'symbol_id' => 20, // হারিকেন (hurricane-lantern)
                'color' => '#FF8C00',
                'founded' => '২০০৮',
                'registration_number' => '021',
                'registration_date' => '2008-11-13',
                'chairman' => 'বেগম জুবেদা কাদের চৌধুরী',
                'secretary_general' => 'আলহাজ্ব কাজী আবুল খায়ের',
                'office_address' => '১১৬/২, বক্স কালভার্ট রোড(৫ম তলা) নয়া পল্টন ঢাকা-১০০০',
                'mobile' => '01711352753, 01711015320',
            ],
            [
                'name' => 'ন্যাশনাল পিপলস্‌ পার্টি (এনপিপি)',
                'name_en' => 'national-peoples-party-npp',
                'logo' => null,
                'symbol_id' => 21, // আম (mango)
                'color' => '#FFD700',
                'founded' => '২০০৮',
                'registration_number' => '022',
                'registration_date' => '2008-11-13',
                'chairman' => 'শেখ ছালাউদ্দিন ছালু',
                'secretary_general' => 'মোঃ ইদ্রিস চৌধুরী',
                'office_address' => '৩১/১, শরীফ কমপ্লেক্স (৬ষ্ঠ তলা), পুরানা পল্টন, ঢাকা-১০০০',
                'mobile' => '01713014492',
            ],
            [
                'name' => 'জমিয়তে উলামায়ে ইসলাম বাংলাদেশ',
                'name_en' => 'jamiate-ulama-e-islam-bangladesh',
                'logo' => null,
                'symbol_id' => 22, // খেজুরগাছ (date-palm)
                'color' => '#228B22',
                'founded' => '২০০৮',
                'registration_number' => '023',
                'registration_date' => '2008-11-13',
                'chairman' => 'মাওলানা শায়খ জিয়া উদ্দিন',
                'secretary_general' => 'মাওলানা মঞ্জুরুল ইসলাম আফেন্দী',
                'office_address' => 'লেভেল ১০, রুম নং ১০০৩/এ, ৫১-৫১/এ, পুরানা পল্টন, ঢাকা',
                'mobile' => '01713-004439, 01712-789220',
                'email' => 'jamiateulamaeislam.bd23@gmail.com',
            ],
            [
                'name' => 'গণফোরাম',
                'name_en' => 'gano-forum',
                'logo' => null,
                'symbol_id' => 23, // উদীয়মান সূর্য (rising-sun)
                'color' => '#FF6347',
                'founded' => '২০০৮',
                'registration_number' => '024',
                'registration_date' => '2008-11-13',
                'chairman' => 'ড. কামাল হোসেন',
                'secretary_general' => 'ডা. মোঃ মিজানুর রহমান',
                'office_address' => '৩২, পুরানা পল্টন, সুলতান আহমেদ প্লাজা (১২ তলা, রুম নং-১২০৫), ঢাকা-১০০০',
                'phone' => '01711154777',
                'email' => 'gonoforum1993.bd@gmail.com',
            ],
            [
                'name' => 'গণফ্রন্ট',
                'name_en' => 'gano-front',
                'logo' => null,
                'symbol_id' => 24, // মাছ (fish)
                'color' => '#1E90FF',
                'founded' => '২০০৮',
                'registration_number' => '025',
                'registration_date' => '2008-11-13',
                'chairman' => 'মোঃ জাকির হোসেন',
                'secretary_general' => 'আহমেদ আলী শেখ',
                'office_address' => '২৭/৭ তোপখানা রোড, বিজয়নগর, ঢাকা-১০০০',
                'phone' => '9551332',
                'fax' => '9567757',
                'mobile' => '01711526677',
            ],
            [
                'name' => 'বাংলাদেশ ন্যাশনাল আওয়ামী পার্টি-বাংলাদেশ ন্যাপ',
                'name_en' => 'bangladesh-national-awami-party-bangladesh-nap',
                'logo' => null,
                'symbol_id' => 25, // গাভী (cow)
                'color' => '#8B4513',
                'founded' => '২০০৮',
                'registration_number' => '027',
                'registration_date' => '2008-11-13',
                'chairman' => 'জেবেল রহমান গাণি',
                'secretary_general' => 'এম. গোলাম মোস্তফা ভুইয়া',
                'office_address' => 'ওরিন টাওয়ার, লিফট ৮, প্লট ২৩, সড়ক ১১৩এ, গুলশান, ঢাকা-১২১২',
                'mobile' => '01711527242, 01716225846, 01711201929',
                'email' => 'sgbnap1957@gmail.com, jghaani.bdnap@gmail.com',
            ],
            [
                'name' => 'বাংলাদেশ জাতীয় পার্টি',
                'name_en' => 'bangladesh-jatiya-party',
                'logo' => null,
                'symbol_id' => 26, // কাঁঠাল (jackfruit)
                'color' => '#FFD700',
                'founded' => '২০০৮',
                'registration_number' => '028',
                'registration_date' => '2008-11-16',
                'chairman' => 'এ. এন. এম সিরাজুল ইসলাম',
                'secretary_general' => 'জাফর আহমেদ জয়',
                'office_address' => 'মাহাবুব আলম ভবন, ২৬৪/৩/২ নবীনবাগ (তিতাস রোড) খিলগাঁও, ঢাকা-১২১৯',
                'mobile' => '01711461440',
                'email' => 'bangladeshjatioaparty.028@gmail.com',
            ],
            [
                'name' => 'ইসলামিক ফ্রন্ট বাংলাদেশ',
                'name_en' => 'islamic-front-bangladesh',
                'logo' => null,
                'symbol_id' => 27, // চেয়ার (chair)
                'color' => '#006747',
                'founded' => '২০০৮',
                'registration_number' => '030',
                'registration_date' => '2008-11-16',
                'chairman' => 'সৈয়দ বাহাদুর শাহ মোজাদ্দেদী',
                'secretary_general' => 'আবুল বাশার মুহাম্মদ জয়নুল আবেদীন জুবাইর',
                'office_address' => 'কাব্যকস সুপার মার্কেট, কক্ষ-৫ (১০ম তলা), প্লট-৩ডি, কাওরান বাজার, তেজগাঁও, ঢাকা-১২১৫',
                'mobile' => '01713011096, 01554316043',
                'email' => 'islamicfrontbangladesh30@gmail.com',
            ],
            [
                'name' => 'বাংলাদেশ কল্যাণ পার্টি',
                'name_en' => 'bangladesh-kallyan-party',
                'logo' => null,
                'symbol_id' => 28, // হাতঘড়ি (wristwatch)
                'color' => '#4169E1',
                'founded' => '২০০৮',
                'registration_number' => '031',
                'registration_date' => '2008-11-17',
                'chairman' => 'মেজর জেনারেল অব. সৈয়দ মুহাম্মদ ইবরাহিম, বীর প্রতীক',
                'secretary_general' => 'আবদুল আউয়াল মামুন',
                'office_address' => 'বাড়ী নং - ৩২৫, লেইন নং-২২, নিউ ডি ও এইচ এস মহাখালী, ঢাকা- ১২০৬',
                'phone' => '88028713733',
                'fax' => '88028824066',
                'mobile' => '01845984201',
                'email' => 'kallyanparty07@gmail.com',
                'website' => 'www.bkp-bd.org',
            ],
            [
                'name' => 'ইসলামী ঐক্যজোট',
                'name_en' => 'islami-oikya-jote',
                'logo' => null,
                'symbol_id' => 29, // মিনার (minaret)
                'color' => '#006747',
                'founded' => '২০০৮',
                'registration_number' => '032',
                'registration_date' => '2008-11-17',
                'chairman' => 'হাফেজ মাওলানা আবুল হাসানাত আমিনী',
                'secretary_general' => 'মুফতী ফয়জুল্লাহ',
                'office_address' => '৫/এ কাজী রিয়াজ উদ্দিন রোড (১ম তলা), পোস্তা চকবাজার, ঢাকা-১২১১',
                'phone' => '8631490',
                'fax' => '8631490',
                'mobile' => '01700-862071, 01712-102605',
                'email' => 'islamioikyajote@gmail.com',
            ],
            [
                'name' => 'বাংলাদেশ খেলাফত মজলিস',
                'name_en' => 'bangladesh-khilafat-majlis',
                'logo' => null,
                'symbol_id' => 30, // রিক্সা (rickshaw)
                'color' => '#FFD700',
                'founded' => '২০০৮',
                'registration_number' => '033',
                'registration_date' => '2008-11-20',
                'chairman' => 'মাওলানা মুহাম্মদ ইসমাঈল নূরপুরী',
                'secretary_general' => 'মাওলানা মামুনুল হক',
                'office_address' => '৫৯/৩/৩ পুরানা পল্টন (৫ম তলা) ঢাকা-১০০০',
                'phone' => '9553693',
                'email' => 'bdkhelafatmajlis@yahoo.com',
            ],
            [
                'name' => 'ইসলামী আন্দোলন বাংলাদেশ',
                'name_en' => 'islami-andolon-bangladesh',
                'logo' => null,
                'symbol_id' => 31, // হাতপাখা (hand-fan)
                'color' => '#006747',
                'founded' => '২০০৮',
                'registration_number' => '034',
                'registration_date' => '2008-11-20',
                'chairman' => 'মুফতী সৈয়দ মুহাম্মদ রেজাউল করীম',
                'secretary_general' => 'ইউনুস আহম্মেদ সেখ',
                'office_address' => '৫৫/বি, পুরানা পল্টন (৩য় তলা), ঢাকা-১০০০',
                'phone' => '9567130, 9586061',
                'fax' => '9567130',
                'email' => 'islamicandolanbd@gmail.com',
            ],
            [
                'name' => 'বাংলাদেশ ইসলামী ফ্রন্ট',
                'name_en' => 'bangladesh-islami-front',
                'logo' => null,
                'symbol_id' => 32, // মোমবাতি (candle)
                'color' => '#FFA500',
                'founded' => '২০০৮',
                'registration_number' => '035',
                'registration_date' => '2008-11-20',
                'chairman' => 'মাওলানা এম,এ, মতিন',
                'secretary_general' => 'অধ্যক্ষ স উ ম আবদুস সামাদ',
                'office_address' => 'ড্রিম আবুল হোসেন টাওয়ার, ২০৭ (৩য় তলা), ১ নং গলি,ফকিরাপুল, মতিঝিল, ঢাকা-১০০০',
                'mobile' => '01819741994, 01819803804',
            ],
            [
                'name' => 'জাতীয় গণতান্ত্রিক পার্টি-জাগপা',
                'name_en' => 'jatiya-gonotantrik-party-jagpa',
                'logo' => null,
                'symbol_id' => 33, // হুক্কা (hookah)
                'color' => '#8B4513',
                'founded' => '২০০৮',
                'registration_number' => '036',
                'registration_date' => '2008-11-20',
            ],
            [
                'name' => 'বাংলাদেশের বিপ্লবী ওয়ার্কার্স পার্টি',
                'name_en' => 'revolutionary-workers-party-of-bangladesh',
                'logo' => null,
                'symbol_id' => 34, // কোদাল (spade)
                'color' => '#DC143C',
                'founded' => '২০০৮',
                'registration_number' => '037',
                'registration_date' => '2008-11-20',
                'secretary_general' => 'সাইফুল হক',
                'office_address' => '২৭/৮-এ, ৪র্থ তলা, তোপখানা রোড, সেগুনবাগিচা, ঢাকা',
                'phone' => '9360303',
                'mobile' => '01711182059, 01688029893',
                'email' => 'biplabiworkersparty@gmail.com',
            ],
            [
                'name' => 'খেলাফত মজলিস',
                'name_en' => 'khilafat-majlis',
                'logo' => null,
                'symbol_id' => 35, // দেওয়াল ঘড়ি (wall-clock)
                'color' => '#006747',
                'founded' => '২০০৮',
                'registration_number' => '038',
                'registration_date' => '2008-11-22',
                'chairman' => 'মাওলানা আব্দুল বাছিত আজাদ',
                'secretary_general' => 'ড. আহমদ আবদুল কাদের',
                'office_address' => '১৬, বিজয়নগর, ৫ম তলা (বিজয়নগর পানির ট্যাংকির পূর্ব পার্শে) ঢাকা-১০০০',
                'phone' => '9354321',
                'mobile' => '01715116152, 01711344812',
                'email' => 'khelafatmajlis@gmail.com',
                'website' => 'www.khelafat-majlis.org',
            ],
            [
                'name' => 'বাংলাদেশ মুসলিম লীগ-বিএমএল',
                'name_en' => 'bangladesh-muslim-league-bml',
                'logo' => null,
                'symbol_id' => 36, // হাত (পাঞ্জা) (hand)
                'color' => '#FF6347',
                'founded' => '২০১৩',
                'registration_number' => '040',
                'registration_date' => '2013-06-02',
                'chairman' => 'এডভোকেট শেখ জুলফিকার বুলবুল চৌধুরী',
                'secretary_general' => 'মোহাম্মদ নজরুল ইসলাম',
                'office_address' => 'স্যুট নং-২০৪, স্বজন টাওয়ার-২, ৩ সেগুন বাগিচা, ঢাকা',
                'phone' => '9894473',
                'mobile' => '01552201396, 01911352945',
                'email' => 'advzbchybmlgs@gmail.com',
            ],
            [
                'name' => 'বাংলাদেশ সাংস্কৃতিক মুক্তিজোট (মুক্তিজোট)',
                'name_en' => 'bangladesh-sangskritik-muktijot',
                'logo' => null,
                'symbol_id' => 37, // ছড়ি (walking-stick)
                'color' => '#4169E1',
                'founded' => '২০১৩',
                'registration_number' => '041',
                'registration_date' => '2013-10-08',
                'chairman' => 'মোঃ শাহজামাল আমিরুল',
                'office_address' => '১৩৭/১০, এস.আর.প্লাজা, লেভেল-১২ (ই), ২য় কলোনী, মাজাররোড, মিরপুর-১, ঢাকা-১২১৬',
                'phone' => '02-8180180',
                'fax' => '02-8180181',
                'mobile' => '01711132632, 01717657349',
                'email' => 'info@muktijot.org',
            ],
            [
                'name' => 'বাংলাদেশ ন্যাশনালিস্ট ফ্রন্ট-বিএনএফ',
                'name_en' => 'bangladesh-nationalist-front-bnf',
                'logo' => null,
                'symbol_id' => 38, // টেলিভিশন (television)
                'color' => '#0066CC',
                'founded' => '২০১৩',
                'registration_number' => '042',
                'registration_date' => '2013-11-18',
                'chairman' => 'এস এম আবুল কালাম আজাদ',
                'office_address' => 'বাড়ি নং-১১৪৪, ফ্লাট-৫এ, রোড নং-৯/এ, এভিনিউ-১০ মিরপুর ডিওএইচএস, ঢাকা-১২১৬',
                'mobile' => '01819194404',
                'email' => 'bnf.azad@gmail.com',
            ],
            [
                'name' => 'জাতীয়তাবাদী গণতান্ত্রিক আন্দোলন-এনডিএম',
                'name_en' => 'jatiyatabadi-gonotantrik-andolon-ndm',
                'logo' => null,
                'symbol_id' => 39, // সিংহ (lion)
                'color' => '#FFD700',
                'founded' => '২০১৯',
                'registration_number' => '043',
                'registration_date' => '2019-01-30',
                'chairman' => 'ববি হাজ্জাজ',
                'secretary_general' => 'মোমিনুল আমিন',
                'office_address' => '২৬০/৬, মালিবাগ মোড়, কক্ষ নং-৬০৫, শাহাজানপুর, ঢাকা-১২১৭',
                'mobile' => '01734530449, 01913-940839',
                'email' => 'communication.ndm@gmail.com',
                'website' => 'www.ndmbd.org',
            ],
            [
                'name' => 'বাংলাদেশ কংগ্রেস',
                'name_en' => 'bangladesh-congress',
                'logo' => null,
                'symbol_id' => 40, // ডাব (green-coconut)
                'color' => '#1E90FF',
                'founded' => '২০১৯',
                'registration_number' => '044',
                'registration_date' => '2019-05-09',
                'chairman' => 'এ্যাডভোকেট কাজী রেজাউল হোসেন',
                'secretary_general' => 'এ্যাডভোকেট মোঃ ইয়ারুল ইসলাম',
                'office_address' => 'হ্যাপি রহমান প্লাজা-(৪র্থ তলা), ২৫-২৭ কাজী নজরুল ইসলাম এভিনিউ, বাংলামটর, ঢাকা-১০০০',
                'mobile' => '01711695138',
                'email' => 'adv.kazirezaul@gmail.com',
                'website' => 'www.bangladeshcongress.org',
            ],
            [
                'name' => 'তৃণমূল বিএনপি',
                'name_en' => 'trinamul-bnp',
                'logo' => null,
                'symbol_id' => 41, // সোনালী আঁশ (golden-fiber)
                'color' => '#FFD700',
                'founded' => '২০২৩',
                'registration_number' => '045',
                'registration_date' => '2023-02-16',
                'chairman' => 'এ্যাডভোকেট অন্তরা সেলিমা হুদা',
                'secretary_general' => 'মেজর (অবঃ) ডাঃ শেখ হাবিবুর রহমান',
                'office_address' => '৩৩ তোপখানা রোড, ১৫/সি মেহেরবা প্লাজা (১৬ তলা), পল্টন, ঢাকা-১০০০',
                'mobile' => '01711832882, 01730441124',
                'email' => 'trinomoolbnp@gmail.com',
                'website' => 'trinomoolbnp.com',
            ],
            [
                'name' => 'ইনসানিয়াত বিপ্লব বাংলাদেশ',
                'name_en' => 'insaniyat-biplob-bangladesh',
                'logo' => null,
                'symbol_id' => 42, // আপেল (apple)
                'color' => '#FF0000',
                'founded' => '২০২৩',
                'registration_number' => '046',
                'registration_date' => '2023-05-08',
                'chairman' => 'ইমাম আবু হায়াত',
                'secretary_general' => 'মো: রেহান আফজাল',
                'office_address' => 'হোল্ডিংস নং-০২ (২য় তলা), রোড নং-২৩/সি, গুলশান-১, ঢাকা-১২১২',
                'mobile' => '01786-272829',
                'email' => 'humanityrevolutionbangladesh@gmail.com',
            ],
            [
                'name' => 'বাংলাদেশ জাতীয় সমাজতান্ত্রিক দল-বাংলাদেশ জাসদ',
                'name_en' => 'bangladesh-jatiya-samajtantrik-dal-bangladesh-jasad',
                'logo' => null,
                'symbol_id' => 43, // মটরগাড়ি (কার) (car)
                'color' => '#DC143C',
                'founded' => '২০২৩',
                'registration_number' => '047',
                'registration_date' => '2023-06-18',
                'chairman' => 'শরীফ নুরুল আম্বিয়া',
                'secretary_general' => 'নাজমুল হক প্রধান',
                'office_address' => '২২/১ তোপখানা রোড (৫ম তলা), ঢাকা-১০০০',
                'phone' => '02-57164644',
                'mobile' => '01556328422, 01819419152, 01711600366, 01828126142',
                'email' => 'sharifambia@yahoo.com, prodhan.josod@gmail.com',
            ],
            [
                'name' => 'বাংলাদেশ জাতীয়তাবাদী আন্দোলন-বিএনএম',
                'name_en' => 'bangladesh-jatiyatabadi-andolon-bnm',
                'logo' => null,
                'symbol_id' => 44, // নোঙ্গর (anchor)
                'color' => '#1E90FF',
                'founded' => '২০২৩',
                'registration_number' => '048',
                'registration_date' => '2023-08-10',
                'chairman' => 'শাহ্ মোহাম্মদ আবু জাফর',
                'secretary_general' => 'ড. আবদুর রহমান',
                'office_address' => '১৪/২, ইকবাল রোড, মোহাম্মদপুর, ঢাকা-১২০৭',
                'mobile' => '01711-956614, 01871-006630',
                'email' => 'jagopolitics@gmail.com',
            ],
            [
                'name' => 'বাংলাদেশ সুপ্রীম পার্টি (বি.এস.পি)',
                'name_en' => 'bangladesh-supreme-party-bsp',
                'logo' => null,
                'symbol_id' => 45, // একতারা (ektara)
                'color' => '#FF6347',
                'founded' => '২০২৩',
                'registration_number' => '049',
                'registration_date' => '2023-08-10',
                'chairman' => 'শাহাজাদা সৈয়দ সাইফুদ্দীন আহমদ',
                'secretary_general' => 'বীর মুক্তিযোদ্ধা মোঃ আব্দুল আজিজ সরকার',
                'office_address' => '৮২ শাহ্ আলীবাগ (চতুর্থ তলা), মিরপুর-১, ঢাকা-১২১৬',
                'mobile' => '01707-893309, 01971-344544',
                'email' => 'bspcentralbd@gmail.com',
            ],
            [
                'name' => 'আমার বাংলাদেশ পার্টি (এবি পার্টি)',
                'name_en' => 'amar-bangladesh-party-ab-party',
                'logo' => null,
                'symbol_id' => 46, // ঈগল (eagle)
                'color' => '#8B4513',
                'founded' => '২০২৪',
                'registration_number' => '050',
                'registration_date' => '2024-08-21',
                'chairman' => 'এ এফ এম সোলায়মান চৌধুরী',
                'secretary_general' => 'মজিবুর রহমান ভূঁইয়া (মঞ্জু)',
                'office_address' => 'সায়হাম স্কাই ভিউ টাওয়ার, ৪র্থ তলা, ৪৫ বিজয় নগর রোড, ঢাকা-১০০০',
                'mobile' => '01711945604, 01711933168',
                'email' => 'abparty2020@gmail.com',
            ],
            [
                'name' => 'গণঅধিকার পরিষদ (জিওপি)',
                'name_en' => 'gano-odhikar-parishad-gop',
                'logo' => null,
                'symbol_id' => 47, // ট্রাক (truck)
                'color' => '#4169E1',
                'founded' => '২০২৪',
                'registration_number' => '051',
                'registration_date' => '2024-09-02',
                'chairman' => 'মোঃ নুরুল হক (নুর)',
                'secretary_general' => 'মোঃ রাশেদ খাঁন',
                'office_address' => 'আল রাজী কমপ্লেক্স (৩য় তলা), বিজয়নগর, পুরানা পল্টন, ঢাকা-১০০০',
                'mobile' => '01758-821025, 01739-195639',
                'email' => 'gopoffice21@gmail.com',
            ],
            [
                'name' => 'নাগরিক ঐক্য',
                'name_en' => 'nagorik-oikko',
                'logo' => null,
                'symbol_id' => 48, // কেটলি (kettle)
                'color' => '#FF6347',
                'founded' => '২০২৪',
                'registration_number' => '052',
                'registration_date' => '2024-09-02',
                'chairman' => 'মাহমুদুর রহমান মান্না',
                'secretary_general' => 'শহীদুল্লাহ কায়সার',
                'office_address' => '২২/১, তোপখানা রোড, ঢাকা-১০০০',
                'mobile' => '01936-755754',
                'email' => 'mail.oikko@gmail.com',
            ],
            [
                'name' => 'গণসংহতি আন্দোলন',
                'name_en' => 'gano-sangati-andolon',
                'logo' => null,
                'symbol_id' => 49, // মাথাল (mathal)
                'color' => '#DC143C',
                'founded' => '২০২৪',
                'registration_number' => '053',
                'registration_date' => '2024-09-17',
                'chairman' => 'জনাব জোনায়েদ সাকি',
                'secretary_general' => 'জনাব আবুল হাসান রুবেল',
                'office_address' => '৩০৬-৩০৭ রোজ ভিউ প্লাজা, ১৮৫ বীর উত্তম সি আর দত্ত রোড, হাতিরপুল, ঢাকা-১০০৫',
                'mobile' => '01715-189545, 01721-623627',
                'email' => 'ganosamhati.cec@gmail.com',
            ],
            [
                'name' => 'বাংলাদেশ ডেভেলপমেন্ট পার্টি',
                'name_en' => 'bangladesh-development-party',
                'logo' => null,
                'symbol_id' => 50, // ফুলকপি (cauliflower)
                'color' => '#90EE90',
                'founded' => '২০২৫',
                'registration_number' => '054',
                'registration_date' => '2025-02-02',
                'chairman' => 'অ্যাড. এ কে এম আনোয়ারুল ইসলাম চান',
                'secretary_general' => 'মুহা. নিজামুল হক নাঈম',
                'office_address' => 'রিসোর্সফুল পল্টন সিটি, ফ্ল্যাট নং-৬০৪, ৫১/৫১-এ, পুরানা পল্টন, ঢাকা-১০০০',
                'mobile' => '01711-007475, 01712-999239',
                'email' => 'bdevelopmentparty@gmail.com, advanwar.chan@gmail.com',
            ],
            [
                'name' => 'বাংলাদেশ মাইনরিটি জনতা পার্টি (বিএমজেপি)',
                'name_en' => 'bangladesh-minority-janata-party-bmjp',
                'logo' => null,
                'symbol_id' => 51, // রকেট (rocket)
                'color' => '#FF6347',
                'founded' => '২০২৫',
                'registration_number' => '055',
                'registration_date' => '2025-04-09',
                'chairman' => 'সুকৃতি কুমার মন্ডল',
                'secretary_general' => 'দিলীপ দাস',
                'office_address' => '৪৩/এ ইন্দ্রিরা রোড, তেজগাঁও, শের-ই বাংলা নগর, ঢাকা-১২১৫',
                'mobile' => '01711-981552, 01701-307807',
                'email' => 'bmjp2017@gmail.com, bmjpofficemail@gmail.com',
            ],
            [
                'name' => 'বাংলাদেশ লেবার পার্টি',
                'name_en' => 'bangladesh-labour-party',
                'logo' => null,
                'symbol_id' => 52, // আনারস (pineapple)
                'color' => '#FFD700',
                'founded' => '২০২৫',
                'registration_number' => '056',
                'registration_date' => '2025-09-25',
                'chairman' => 'ডাঃ মোস্তাফিজুর রহমান ইরান',
                'secretary_general' => 'ইঞ্জিনিয়ার ফরিদ উদ্দিন',
                'office_address' => '৮৫/১ নয়াপল্টন মসজিদ গলি (তৃতীয় তলা), ঢাকা-১০০০',
                'phone' => '+88028-48312699',
                'mobile' => '01711-004277, 01820-576330',
                'email' => 'labourparty2018@gmail.com',
            ],
            [
                'name' => 'বাংলাদেশ রিপাবলিকান পার্টি (বিআরপি)',
                'name_en' => 'bangladesh-republican-party-brp',
                'logo' => null,
                'symbol_id' => 53, // হাতি (elephant)
                'color' => '#808080',
                'founded' => '২০২৫',
                'registration_number' => '057',
                'registration_date' => '2025-10-23',
                'chairman' => 'মোঃ আবু হানিফ হৃদয়',
                'office_address' => '৮৮/১, শহীদ ফারুক রোড (৩য় তলা), দক্ষিণ যাত্রাবাড়ী, ঢাকা-১২০৪',
                'mobile' => '01531-833848',
                'email' => 'republicanparty2014@gmail.com',
                'website' => 'www.republicanpartybd.com',
            ],
        ];

        foreach ($parties as $party) {
            Party::create($party);
        }
    }
}
